<a href="https://colab.research.google.com/github/bl00p1ng/Curso-analisis-de-datos-con-Pandas-y-Python/blob/main/primeros_pasos_con_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso de Manipulación y Análisis de Datos con Pandas y Python

## 📚 Módulo 1. Comenzando con pandas

### Clase 2. Primeros pasos con Google Colab: configuración del entorno de trabajo

Por defecto las listas en Python no cuentan con capacidades matemáticas, por eso al usarse el operador `+` entre listas se efectua una concatenación y no una suma.

In [2]:
[1, 2, 3, 4, 5] + [10]

[1, 2, 3, 4, 5, 10]

Para poder sumar un valor a caada uno de los elementos de un vetor es necesario usar **numpy**, una librería usada para análisis númerico

In [3]:
import numpy as np

In [4]:
# np.array() crea un vector con capacidades matemáticas
np.array([1, 2, 3, 4, 5]) + 10

array([11, 12, 13, 14, 15])

Para conocer las dimenciones de un vector se puede usar la propiedad `shape` de `numpy.array()`. Esta regresa una tula con las dimenciones del vector.

In [5]:
np.array([1, 2, 3, 4, 5]).shape

(5,)

In [13]:
# Crear un Array de múltiples dimenciones
matrix = np.array([[1, 2, 3, 4], [6, 7, 8, 9]])
print(matrix, '\n')

print(f'Dimenciones: {matrix.shape}')

[[1 2 3 4]
 [6 7 8 9]] 

Dimenciones: (2, 4)


Para acceder a los elementos de la matriz se usa la notación de `[]` para acceder a las filas y columnas de la matriz usando su índice

In [15]:
# Acceder a la primera fila de la matriz
matrix[0]

# Obtener un elemento específico de uan fila de la matriz
matrix[0][2]

3